site_name: Container Incubator
theme:
  name: material
  language: en

  icon: 
    logo: material/docker

  palette:
    # Pallete toggle for night mode
    - scheme: default
      primary: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for light mode
    - scheme: slate
      primary: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.path
    - search.highlight
    - search.share

  plugins:
    - search
    - social

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/mateusztylec
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/mateusztylec
    - icon: fontawesome/brands/github
      link: https://github.com/mateusztylec

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


repo_url: https://github.com/mateusztylec/selfhosted-with-docker

copyright: Copyright &copy; 2023 Mateusz Tylec