name: Deploy

on:
  push:
    branches:
      - "main"  

jobs:
  deploy-cloud:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2 
      - name: deploying to cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.PORT}}
          script: |
            cd /docker_images/mkdocs
            sudo docker-compose up -d
